AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - test/**/*.rb
  NewCops: enable

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 119 # line length on GitHub's PR pages

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
