version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.0.3
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "zaikio-loom.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: gem install bundler && bundle install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "zaikio-loom.gemspec" }}

      - run: bundle exec rake test

  publish:
    docker:
      - image: cimg/ruby:3.0.3

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build package
          command: gem build zaikio-loom.gemspec
      - run:
          name: Push package
          command: |
            VERSION=$(ruby -r "./lib/zaikio/loom/version.rb" -e "print Zaikio::Loom::VERSION")
            gem push zaikio-loom-${VERSION}.gem

workflows:
  default:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish:
          context:
            - rubygems-push
          requires: [test]
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
